// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.27.0
// source: src/grpc/proto/notification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = 'notification'

/** Common types */
export enum NotificationType {
  EMAIL = 0,
  SMS = 1,
  PUSH = 2,
  WEBHOOK = 3,
  UNRECOGNIZED = -1,
}

export function notificationTypeFromJSON(object: any): NotificationType {
  switch (object) {
    case 0:
    case 'EMAIL':
      return NotificationType.EMAIL
    case 1:
    case 'SMS':
      return NotificationType.SMS
    case 2:
    case 'PUSH':
      return NotificationType.PUSH
    case 3:
    case 'WEBHOOK':
      return NotificationType.WEBHOOK
    case -1:
    case 'UNRECOGNIZED':
    default:
      return NotificationType.UNRECOGNIZED
  }
}

export function notificationTypeToJSON(object: NotificationType): string {
  switch (object) {
    case NotificationType.EMAIL:
      return 'EMAIL'
    case NotificationType.SMS:
      return 'SMS'
    case NotificationType.PUSH:
      return 'PUSH'
    case NotificationType.WEBHOOK:
      return 'WEBHOOK'
    case NotificationType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

export enum NotificationStatus {
  PENDING = 0,
  SENT = 1,
  DELIVERED = 2,
  FAILED = 3,
  RETRY = 4,
  UNRECOGNIZED = -1,
}

export function notificationStatusFromJSON(object: any): NotificationStatus {
  switch (object) {
    case 0:
    case 'PENDING':
      return NotificationStatus.PENDING
    case 1:
    case 'SENT':
      return NotificationStatus.SENT
    case 2:
    case 'DELIVERED':
      return NotificationStatus.DELIVERED
    case 3:
    case 'FAILED':
      return NotificationStatus.FAILED
    case 4:
    case 'RETRY':
      return NotificationStatus.RETRY
    case -1:
    case 'UNRECOGNIZED':
    default:
      return NotificationStatus.UNRECOGNIZED
  }
}

export function notificationStatusToJSON(object: NotificationStatus): string {
  switch (object) {
    case NotificationStatus.PENDING:
      return 'PENDING'
    case NotificationStatus.SENT:
      return 'SENT'
    case NotificationStatus.DELIVERED:
      return 'DELIVERED'
    case NotificationStatus.FAILED:
      return 'FAILED'
    case NotificationStatus.RETRY:
      return 'RETRY'
    case NotificationStatus.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

export enum NotificationPriority {
  LOW = 0,
  NORMAL = 1,
  HIGH = 2,
  URGENT = 3,
  UNRECOGNIZED = -1,
}

export function notificationPriorityFromJSON(
  object: any
): NotificationPriority {
  switch (object) {
    case 0:
    case 'LOW':
      return NotificationPriority.LOW
    case 1:
    case 'NORMAL':
      return NotificationPriority.NORMAL
    case 2:
    case 'HIGH':
      return NotificationPriority.HIGH
    case 3:
    case 'URGENT':
      return NotificationPriority.URGENT
    case -1:
    case 'UNRECOGNIZED':
    default:
      return NotificationPriority.UNRECOGNIZED
  }
}

export function notificationPriorityToJSON(
  object: NotificationPriority
): string {
  switch (object) {
    case NotificationPriority.LOW:
      return 'LOW'
    case NotificationPriority.NORMAL:
      return 'NORMAL'
    case NotificationPriority.HIGH:
      return 'HIGH'
    case NotificationPriority.URGENT:
      return 'URGENT'
    case NotificationPriority.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

/** Send single notification */
export interface SendNotificationRequest {
  /** Unique event identifier */
  eventId: string
  /** Recipient user ID */
  userId: string
  /** Notification type */
  type: NotificationType
  /** Template identifier */
  templateId: string
  /** Template variables */
  payload: { [key: string]: string }
  priority: NotificationPriority
  /** Max retry attempts */
  retryCount: number
  /** Timeout in milliseconds */
  timeoutMs: number
  /** Auth/tracking metadata */
  metadata: { [key: string]: string }
}

export interface SendNotificationRequest_PayloadEntry {
  key: string
  value: string
}

export interface SendNotificationRequest_MetadataEntry {
  key: string
  value: string
}

export interface SendNotificationResponse {
  success: boolean
  notificationId: string
  message: string
  status: NotificationStatus
  timestamp: number
}

function createBaseSendNotificationRequest(): SendNotificationRequest {
  return {
    eventId: '',
    userId: '',
    type: 0,
    templateId: '',
    payload: {},
    priority: 0,
    retryCount: 0,
    timeoutMs: 0,
    metadata: {},
  }
}

export const SendNotificationRequest: MessageFns<SendNotificationRequest> = {
  encode(
    message: SendNotificationRequest,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.eventId !== '') {
      writer.uint32(10).string(message.eventId)
    }
    if (message.userId !== '') {
      writer.uint32(18).string(message.userId)
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type)
    }
    if (message.templateId !== '') {
      writer.uint32(34).string(message.templateId)
    }
    Object.entries(message.payload).forEach(([key, value]) => {
      SendNotificationRequest_PayloadEntry.encode(
        { key: key as any, value },
        writer.uint32(42).fork()
      ).join()
    })
    if (message.priority !== 0) {
      writer.uint32(48).int32(message.priority)
    }
    if (message.retryCount !== 0) {
      writer.uint32(56).int32(message.retryCount)
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(64).int32(message.timeoutMs)
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      SendNotificationRequest_MetadataEntry.encode(
        { key: key as any, value },
        writer.uint32(74).fork()
      ).join()
    })
    return writer
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number
  ): SendNotificationRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSendNotificationRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.eventId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.userId = reader.string()
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.type = reader.int32() as any
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.templateId = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          const entry5 = SendNotificationRequest_PayloadEntry.decode(
            reader,
            reader.uint32()
          )
          if (entry5.value !== undefined) {
            message.payload[entry5.key] = entry5.value
          }
          continue
        }
        case 6: {
          if (tag !== 48) {
            break
          }

          message.priority = reader.int32() as any
          continue
        }
        case 7: {
          if (tag !== 56) {
            break
          }

          message.retryCount = reader.int32()
          continue
        }
        case 8: {
          if (tag !== 64) {
            break
          }

          message.timeoutMs = reader.int32()
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          const entry9 = SendNotificationRequest_MetadataEntry.decode(
            reader,
            reader.uint32()
          )
          if (entry9.value !== undefined) {
            message.metadata[entry9.key] = entry9.value
          }
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): SendNotificationRequest {
    return {
      eventId: isSet(object.eventId) ? globalThis.String(object.eventId) : '',
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      type: isSet(object.type) ? notificationTypeFromJSON(object.type) : 0,
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : '',
      payload: isObject(object.payload)
        ? Object.entries(object.payload).reduce<{ [key: string]: string }>(
            (acc, [key, value]) => {
              acc[key] = String(value)
              return acc
            },
            {}
          )
        : {},
      priority: isSet(object.priority)
        ? notificationPriorityFromJSON(object.priority)
        : 0,
      retryCount: isSet(object.retryCount)
        ? globalThis.Number(object.retryCount)
        : 0,
      timeoutMs: isSet(object.timeoutMs)
        ? globalThis.Number(object.timeoutMs)
        : 0,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>(
            (acc, [key, value]) => {
              acc[key] = String(value)
              return acc
            },
            {}
          )
        : {},
    }
  },

  toJSON(message: SendNotificationRequest): unknown {
    const obj: any = {}
    if (message.eventId !== '') {
      obj.eventId = message.eventId
    }
    if (message.userId !== '') {
      obj.userId = message.userId
    }
    if (message.type !== 0) {
      obj.type = notificationTypeToJSON(message.type)
    }
    if (message.templateId !== '') {
      obj.templateId = message.templateId
    }
    if (message.payload) {
      const entries = Object.entries(message.payload)
      if (entries.length > 0) {
        obj.payload = {}
        entries.forEach(([k, v]) => {
          obj.payload[k] = v
        })
      }
    }
    if (message.priority !== 0) {
      obj.priority = notificationPriorityToJSON(message.priority)
    }
    if (message.retryCount !== 0) {
      obj.retryCount = Math.round(message.retryCount)
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs)
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata)
      if (entries.length > 0) {
        obj.metadata = {}
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v
        })
      }
    }
    return obj
  },

  create<I extends Exact<DeepPartial<SendNotificationRequest>, I>>(
    base?: I
  ): SendNotificationRequest {
    return SendNotificationRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SendNotificationRequest>, I>>(
    object: I
  ): SendNotificationRequest {
    const message = createBaseSendNotificationRequest()
    message.eventId = object.eventId ?? ''
    message.userId = object.userId ?? ''
    message.type = object.type ?? 0
    message.templateId = object.templateId ?? ''
    message.payload = Object.entries(object.payload ?? {}).reduce<{
      [key: string]: string
    }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value)
      }
      return acc
    }, {})
    message.priority = object.priority ?? 0
    message.retryCount = object.retryCount ?? 0
    message.timeoutMs = object.timeoutMs ?? 0
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{
      [key: string]: string
    }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value)
      }
      return acc
    }, {})
    return message
  },
}

function createBaseSendNotificationRequest_PayloadEntry(): SendNotificationRequest_PayloadEntry {
  return { key: '', value: '' }
}

export const SendNotificationRequest_PayloadEntry: MessageFns<SendNotificationRequest_PayloadEntry> =
  {
    encode(
      message: SendNotificationRequest_PayloadEntry,
      writer: BinaryWriter = new BinaryWriter()
    ): BinaryWriter {
      if (message.key !== '') {
        writer.uint32(10).string(message.key)
      }
      if (message.value !== '') {
        writer.uint32(18).string(message.value)
      }
      return writer
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number
    ): SendNotificationRequest_PayloadEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input)
      const end = length === undefined ? reader.len : reader.pos + length
      const message = createBaseSendNotificationRequest_PayloadEntry()
      while (reader.pos < end) {
        const tag = reader.uint32()
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break
            }

            message.key = reader.string()
            continue
          }
          case 2: {
            if (tag !== 18) {
              break
            }

            message.value = reader.string()
            continue
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break
        }
        reader.skip(tag & 7)
      }
      return message
    },

    fromJSON(object: any): SendNotificationRequest_PayloadEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : '',
        value: isSet(object.value) ? globalThis.String(object.value) : '',
      }
    },

    toJSON(message: SendNotificationRequest_PayloadEntry): unknown {
      const obj: any = {}
      if (message.key !== '') {
        obj.key = message.key
      }
      if (message.value !== '') {
        obj.value = message.value
      }
      return obj
    },

    create<
      I extends Exact<DeepPartial<SendNotificationRequest_PayloadEntry>, I>,
    >(base?: I): SendNotificationRequest_PayloadEntry {
      return SendNotificationRequest_PayloadEntry.fromPartial(
        base ?? ({} as any)
      )
    },
    fromPartial<
      I extends Exact<DeepPartial<SendNotificationRequest_PayloadEntry>, I>,
    >(object: I): SendNotificationRequest_PayloadEntry {
      const message = createBaseSendNotificationRequest_PayloadEntry()
      message.key = object.key ?? ''
      message.value = object.value ?? ''
      return message
    },
  }

function createBaseSendNotificationRequest_MetadataEntry(): SendNotificationRequest_MetadataEntry {
  return { key: '', value: '' }
}

export const SendNotificationRequest_MetadataEntry: MessageFns<SendNotificationRequest_MetadataEntry> =
  {
    encode(
      message: SendNotificationRequest_MetadataEntry,
      writer: BinaryWriter = new BinaryWriter()
    ): BinaryWriter {
      if (message.key !== '') {
        writer.uint32(10).string(message.key)
      }
      if (message.value !== '') {
        writer.uint32(18).string(message.value)
      }
      return writer
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number
    ): SendNotificationRequest_MetadataEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input)
      const end = length === undefined ? reader.len : reader.pos + length
      const message = createBaseSendNotificationRequest_MetadataEntry()
      while (reader.pos < end) {
        const tag = reader.uint32()
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break
            }

            message.key = reader.string()
            continue
          }
          case 2: {
            if (tag !== 18) {
              break
            }

            message.value = reader.string()
            continue
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break
        }
        reader.skip(tag & 7)
      }
      return message
    },

    fromJSON(object: any): SendNotificationRequest_MetadataEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : '',
        value: isSet(object.value) ? globalThis.String(object.value) : '',
      }
    },

    toJSON(message: SendNotificationRequest_MetadataEntry): unknown {
      const obj: any = {}
      if (message.key !== '') {
        obj.key = message.key
      }
      if (message.value !== '') {
        obj.value = message.value
      }
      return obj
    },

    create<
      I extends Exact<DeepPartial<SendNotificationRequest_MetadataEntry>, I>,
    >(base?: I): SendNotificationRequest_MetadataEntry {
      return SendNotificationRequest_MetadataEntry.fromPartial(
        base ?? ({} as any)
      )
    },
    fromPartial<
      I extends Exact<DeepPartial<SendNotificationRequest_MetadataEntry>, I>,
    >(object: I): SendNotificationRequest_MetadataEntry {
      const message = createBaseSendNotificationRequest_MetadataEntry()
      message.key = object.key ?? ''
      message.value = object.value ?? ''
      return message
    },
  }

function createBaseSendNotificationResponse(): SendNotificationResponse {
  return {
    success: false,
    notificationId: '',
    message: '',
    status: 0,
    timestamp: 0,
  }
}

export const SendNotificationResponse: MessageFns<SendNotificationResponse> = {
  encode(
    message: SendNotificationResponse,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success)
    }
    if (message.notificationId !== '') {
      writer.uint32(18).string(message.notificationId)
    }
    if (message.message !== '') {
      writer.uint32(26).string(message.message)
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status)
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp)
    }
    return writer
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number
  ): SendNotificationResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSendNotificationResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.success = reader.bool()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.notificationId = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.message = reader.string()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.status = reader.int32() as any
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.timestamp = longToNumber(reader.int64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): SendNotificationResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
      notificationId: isSet(object.notificationId)
        ? globalThis.String(object.notificationId)
        : '',
      message: isSet(object.message) ? globalThis.String(object.message) : '',
      status: isSet(object.status)
        ? notificationStatusFromJSON(object.status)
        : 0,
      timestamp: isSet(object.timestamp)
        ? globalThis.Number(object.timestamp)
        : 0,
    }
  },

  toJSON(message: SendNotificationResponse): unknown {
    const obj: any = {}
    if (message.success !== false) {
      obj.success = message.success
    }
    if (message.notificationId !== '') {
      obj.notificationId = message.notificationId
    }
    if (message.message !== '') {
      obj.message = message.message
    }
    if (message.status !== 0) {
      obj.status = notificationStatusToJSON(message.status)
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<SendNotificationResponse>, I>>(
    base?: I
  ): SendNotificationResponse {
    return SendNotificationResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SendNotificationResponse>, I>>(
    object: I
  ): SendNotificationResponse {
    const message = createBaseSendNotificationResponse()
    message.success = object.success ?? false
    message.notificationId = object.notificationId ?? ''
    message.message = object.message ?? ''
    message.status = object.status ?? 0
    message.timestamp = object.timestamp ?? 0
    return message
  },
}

export interface NotificationService {
  SendNotification(
    request: SendNotificationRequest
  ): Promise<SendNotificationResponse>
}

export const NotificationServiceServiceName = 'notification.NotificationService'
export class NotificationServiceClientImpl implements NotificationService {
  private readonly rpc: Rpc
  private readonly service: string
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || NotificationServiceServiceName
    this.rpc = rpc
    this.SendNotification = this.SendNotification.bind(this)
  }
  SendNotification(
    request: SendNotificationRequest
  ): Promise<SendNotificationResponse> {
    const data = SendNotificationRequest.encode(request).finish()
    const promise = this.rpc.request(this.service, 'SendNotification', data)
    return promise.then((data) =>
      SendNotificationResponse.decode(new BinaryReader(data))
    )
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array
  ): Promise<Uint8Array>
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never
    }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
