export enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  DUPLICATE_DATA = 'DUPLICATE',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
}
